### PR TITLE
Feature/ja-25 add localization

### PR DESCRIPTION
**Pull request by GrzegorzKmiecinski**

### CODE REVIEW

**Review by Zjyslav — CHANGES_REQUESTED** [review]
Overall great work, but I found some things to correct in English version:
- [x] `Home/Index` - link says "Your class dates", but the page it links to says "Your schedule" - I'd make it the latter in both cases.
- [x] `Home/Tutor`: the header is not translated and first item on list of links is just "Add" - I'd change it to "Create ad" (on "New ad" to be consistent with what you see after clicking it)
- [x] `Browse/Ads` - page number on the bottom is not translated
- [x] `Shared/Components/CreateRequestForAd` - form labels are not translated - you need to replace `@Html.DisplayNameFor` with resource (and I think remove `asp-for` from label).
- [x] `Tutor/CreateScheduleItem` - button is in Polish
- [x] I would change in Polish version `Funkcjonalność studenta` to `Funkcjonalność ucznia`

**Review by Zjyslav — CHANGES_REQUESTED** [review]
- [x] `Home/Tutor` - header is still in Polish
- [x] `Tutor/CreateScheduleItem` - header is in Polish
- [ ] Merge develop and resolve conflicts

**Comment by GrzegorzKmiecinski** [comment]
>     * [ ]  Merge develop and resolve conflicts

There're no conflicts in the VS but GH shows it's something with blazor. @Zjyslav can you take a look?

conflicts

**Comment by Zjyslav** [comment]
> > ```
> > * [ ]  Merge develop and resolve conflicts
> > ```
> 
> There're no conflicts in the VS but GH shows it's something with blazor. @Zjyslav can you take a look?
> 
> conflicts

Whole `Schedule` view had to be replaced with a Blazor component.

**Review by Zjyslav — APPROVED** [review]

**Pull request merged**
