### PR TITLE
Feature/ja 55 schedule item request controller

### PR DESCRIPTION
**Pull request by skrawus**
Created controller `ScheduleItemRequestController` and fixed a few issues. I also deleted the checkboxes `IsAccepted`, because students should not be able to accept themselves for classes.

### CODE REVIEW

**Comment by skrawus** [comment]
I'm now wondering about the checkboxes - where to place them. A student should not be able to check the box, but on the other hand - a tutor should.
Now I think I should ad the option but not sure where exactly. Let me know what you think of this, please

**Comment by Zjyslav** [comment]
> I'm now wondering about the checkboxes - where to place them. A student should not be able to check the box, but on the other hand - a tutor should. Now I think I should ad the option but not sure where exactly. Let me know what you think of this, please

I think we should have all checkboxes now for "admins", but later create a dedicated view for student and tutor, where we remove what they don't need to be able to change.

**Review by Zjyslav — CHANGES_REQUESTED** [review]
- remove `Id` from Create and Edit views (setting it in Create does nothing, changing it later on could break references)
- add `IsAccepted` to Create and Edit views (it's not important in Create, but you are using `model.IsAccepted`, when there's no way to set it - if you don't want it in Create I'd go with hardcoding it to `false`)

**Review by GrzegorzKmiecinski — CHANGES_REQUESTED** [review]
As we discussed last time, ScheduleItemRequest model should have IsRemote (bool) property.

**Comment by skrawus** [comment]
Corrected

**Review by Zjyslav — CHANGES_REQUESTED** [review]
Please add `IsRemote` to all views. Right now it's only in Create, should be also in Index, Delete, Details and Edit.

**Review by Zjyslav — APPROVED** [review]

**Review by GrzegorzKmiecinski — APPROVED** [review]

**Pull request merged**
